services:
  # Backend Service - Node.js Express + Prisma
  - type: web
    name: timesheet-backend
    env: node
    plan: free
    rootDir: timesheet-backend
    buildCommand: npm install
    startCommand: npm start
    region: singapore
    nodeVersion: 18.18.2
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: mysql://rice:Rice@2020@203.159.95.167:4406/db_timesheet_sk
      - key: JWT_SECRET
        sync: your_jwt_secret_here
      - key: PORT

