services:
  - type: web
    name: timesheet-backend
    env: node
    plan: free
    rootDir: timesheet-backend
    region: singapore
    nodeVersion: 18.18.2
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    preBuildCommand: npx prisma generate
    buildFilter:
      paths:
        - timesheet-backend/**
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        sync: false
