services:
  # Backend Service - Node.js Express + Prisma
  - type: web
    name: timesheet-backend
    env: node
    plan: free
    rootDir: timesheet-backend
    buildCommand: npm install
    startCommand: npm start
    region: singapore
    nodeVersion: 18.18.2
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        sync: false

  # Frontend Service - React build as Static Site
  - type: static
    name: timesheet-frontend
    plan: free
    rootDir: timesheet-frontend
    buildCommand: npm install && npm run build
    publishDir: build
    autoDeploy: true
    envVars:
      - key: REACT_APP_API
        sync: false
